version: "{build}"
build: off
deploy: off
clone_depth: 1
clone_folder: c:\gopath\src\github.com\ryym\slv

environment:
  GOPATH: c:\gopath

install:
  - go version
  - go env
  - go get -u github.com/golang/dep/cmd/dep
  - "%GOPATH%\\bin\\dep ensure"

test_script:
  - go build main.go
  - go test ./...

notifications: off
